---
title: "Visualizing Team Structures of Winning Kaggle Teams"
author: "Jim Thompson"
date: "August 13, 2015"
output: html_document
---

Building on the data collected for the [Kaggle Leaderboard Medal Count By Country](https://www.kaggle.com/jimthompson/introducing-kaggle-scripts/kaggle-competition-medal-count-analysis)
we examine the structure of winning teams using the **igraph** package.

```{r,echo=FALSE}
# this creates team data from extract of web scraping Kaggle Leaderboard pages
# Web scraping code and data prep can be found at https://github.com/jimthompson5802/kaggle-RScript
raw.team.df <- read.csv(textConnection('
"competition.name","team.type","team.place","team.name","member.name","member.url"
"Heritage Health Prize","team-link team-player",1,"POWERDOT","David Vogel","/users/1941/david-vogel"
"Heritage Health Prize","team-link team-player",1,"POWERDOT","Sali Mali","/users/1335/sali-mali"
"Heritage Health Prize","team-link team-player",1,"POWERDOT","Randy","/users/10634/randy"
"Heritage Health Prize","team-link team-player",1,"POWERDOT","Edward","/users/6395/edward"
"Heritage Health Prize","team-link team-player",1,"POWERDOT","Willem Mestrom","/wmestrom"
"Heritage Health Prize","team-link team-player",1,"POWERDOT","infty","/users/36878/infty"
"Heritage Health Prize","team-link team-player",1,"POWERDOT","random modeler","/users/36885/random-modeler"
"Heritage Health Prize","team-link team-player",2,"EXL Analytics","Sassoon Kosian","/users/11687/sassoon-kosian"
"Heritage Health Prize","team-link team-player",2,"EXL Analytics","DanB","/dansbecker"
"Heritage Health Prize","team-link team-player",2,"EXL Analytics","B Yang","/byang1"
"Heritage Health Prize","team-link team-player",2,"EXL Analytics","Tim Salimans","/timsalimans"
"Heritage Health Prize","team-link single-player",3,"J.A. Guerrero","J.A. Guerrero","/blindape"
"GE Flight Quest","team-link team-player",1,"Gxav & *","Xavier Conort","/xavierconort"
"GE Flight Quest","team-link team-player",1,"Gxav & *","Hong","/users/16215/hong"
"GE Flight Quest","team-link team-player",1,"Gxav & *","geyap","/ghimengyap"
"GE Flight Quest","team-link team-player",1,"Gxav & *","Clifton Phua","/cliftonphua"
"GE Flight Quest","team-link team-player",1,"Gxav & *","BigPlanet","/bigplanet"
"GE Flight Quest","team-link team-player",2,"As High as Honor","Paweł","/paweljankiewicz"
"GE Flight Quest","team-link team-player",2,"As High as Honor","jontix","/jontix"
"GE Flight Quest","team-link single-player",3,"Taki","Taki","/users/6516/g-bor-tak-cs"
"Flight Quest 2: Flight Optimization, Milestone Phase","team-link single-player",1,"id","id","/users/118392/id"
"Flight Quest 2: Flight Optimization, Milestone Phase","team-link single-player",2,"johnsonav","johnsonav","/johnsonav"
"Flight Quest 2: Flight Optimization, Milestone Phase","team-link single-player",3,"Taki","Taki","/users/6516/g-bor-tak-cs"
"Flight Quest 2: Flight Optimization, Main Phase","team-link team-player",1,"Taki & Chris","Gábor Takács","/users/6516/g-bor-tak-cs"
"Flight Quest 2: Flight Optimization, Main Phase","team-link team-player",1,"Taki & Chris","Christian Kiss-Tóth","/users/121535/christian-kiss-t-th"
"Flight Quest 2: Flight Optimization, Main Phase","team-link single-player",2,"Murashka","Murashka","/dmytrolystopad"
"Flight Quest 2: Flight Optimization, Main Phase","team-link single-player",3,"Willem Mestrom","Willem Mestrom","/wmestrom"
"Flight Quest 2: Flight Optimization, Final Phase","team-link single-player",1,"jarfo","jarfo","/users/95601/jos-a-r-fonollosa"
"Flight Quest 2: Flight Optimization, Final Phase","team-link single-player",2,"charango","charango","/sergeykozub"
"Flight Quest 2: Flight Optimization, Final Phase","team-link single-player",3,"Willem Mestrom","Willem Mestrom","/wmestrom"
"National Data Science Bowl","team-link team-player",1,"≋ Deep Sea ≋","sedielem","/sedielem"
"National Data Science Bowl","team-link team-player",1,"≋ Deep Sea ≋","Aaron van den Oord","/users/10849/aaron-van-den-oord"
"National Data Science Bowl","team-link team-player",1,"≋ Deep Sea ≋","Lionel Pigou","/users/176217/lionel-pigou"
"National Data Science Bowl","team-link team-player",1,"≋ Deep Sea ≋","golondrina","/users/190873/golondrina"
"National Data Science Bowl","team-link team-player",1,"≋ Deep Sea ≋","Pieter","/users/197973/pieter"
"National Data Science Bowl","team-link team-player",1,"≋ Deep Sea ≋","jburms","/jburms"
"National Data Science Bowl","team-link team-player",1,"≋ Deep Sea ≋","317070","/users/237639/317070"
"National Data Science Bowl","team-link team-player",2,"Happy Lantern Festival","xudong cao","/users/121486/xudong-cao"
"National Data Science Bowl","team-link team-player",2,"Happy Lantern Festival","gl&hf","/users/164872/gl-hf"
"National Data Science Bowl","team-link team-player",2,"Happy Lantern Festival","Tianqi Chen","/tqchen"
"National Data Science Bowl","team-link team-player",2,"Happy Lantern Festival","Winsty","/winsty"
"National Data Science Bowl","team-link team-player",2,"Happy Lantern Festival","Bing Xu","/binghsu"
"National Data Science Bowl","team-link team-player",3,"Poisson Process","Benjamin Graham","/btgraham"
"National Data Science Bowl","team-link team-player",3,"Poisson Process","Ryan Munion","/iamthep"
"Diabetic Retinopathy Detection","team-link single-player",1,"Min-Pooling","Min-Pooling","/btgraham"
"Diabetic Retinopathy Detection","team-link team-player",2,"o_O","Mathis Antony","/sveitser"
"Diabetic Retinopathy Detection","team-link team-player",2,"o_O","Stephan Brüggemann","/users/286599/stephan-br-ggemann"
"Diabetic Retinopathy Detection","team-link team-player",3,"Reformed Gamblers","John Dunavent","/johndun"
"Diabetic Retinopathy Detection","team-link team-player",3,"Reformed Gamblers","Junonia","/pathbinder"
"Diabetic Retinopathy Detection","team-link team-player",3,"Reformed Gamblers","harkmug","/users/72638/harkmug"
"The Hewlett Foundation: Short Answer Scoring","team-link team-player",1,"Measurement Incorporated","FragLegs","/users/49523/fraglegs"
"The Hewlett Foundation: Short Answer Scoring","team-link team-player",1,"Measurement Incorporated","Justin Fister","/users/12386/justin-fister"
"The Hewlett Foundation: Short Answer Scoring","team-link team-player",1,"Measurement Incorporated","Vik Paruchuri","/vikpar"
"The Hewlett Foundation: Short Answer Scoring","team-link team-player",1,"Measurement Incorporated","David Vaughn","/davidsvaughn"
"The Hewlett Foundation: Short Answer Scoring","team-link single-player",2,"Luis Tandalla","Luis Tandalla","/users/23759/luis-tandalla"
"The Hewlett Foundation: Short Answer Scoring","team-link single-player",3,"Jure Zbontar","Jure Zbontar","/users/835/jure-zbontar"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",1,"SirGuessalot & PlanetThanet & Stefan","Momchil Georgiev","/sirguessalot"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",1,"SirGuessalot & PlanetThanet & Stefan","Jason Tigg","/users/7052/jason-tigg"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",1,"SirGuessalot & PlanetThanet & Stefan","Stefan Henß","/users/7117/stefan-hen"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",2,"@ORGANIZATION","William Cukierski","/wcukierski"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",2,"@ORGANIZATION","Sali Mali","/users/1335/sali-mali"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",2,"@ORGANIZATION","Christopher Hefele","/chefele"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",2,"@ORGANIZATION","Eu Jin Lok","/ejlok1"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",2,"@ORGANIZATION","B Yang","/byang1"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",3,"VikP & jman","Justin Fister","/users/12386/justin-fister"
"The Hewlett Foundation: Automated Essay Scoring","team-link team-player",3,"VikP & jman","Vik Paruchuri","/vikpar"
"Allstate Purchase Prediction Challenge","team-link team-player",1,"Prazaci","maternaj","/maternaj"
"Allstate Purchase Prediction Challenge","team-link team-player",1,"Prazaci","Perroquet","/quickjanca"
"Allstate Purchase Prediction Challenge","team-link team-player",1,"Prazaci","Matfyzak","/lukasdrapal"
"Allstate Purchase Prediction Challenge","team-link team-player",1,"Prazaci","nimo","/users/70466/nimo"
"Allstate Purchase Prediction Challenge","team-link team-player",1,"Prazaci","Emil Skultety","/users/69295/emil-skultety"
"Allstate Purchase Prediction Challenge","team-link team-player",2,"Alessandro & BreakfastPirate","BreakfastPirate","/users/9766/breakfastpirate"
"Allstate Purchase Prediction Challenge","team-link team-player",2,"Alessandro & BreakfastPirate","Alessandro Mariani","/alzmcr"
"Allstate Purchase Prediction Challenge","team-link single-player",3,"Owen","Owen","/owenzhang1"
"Merck Molecular Activity Challenge","team-link team-player",1,"gggg","gggg","/users/45034/gggg"
"Merck Molecular Activity Challenge","team-link team-player",1,"gggg","eep!","/users/56927/eep"
"Merck Molecular Activity Challenge","team-link team-player",1,"gggg","Navdeep Jaitly","/users/61041/navdeep-jaitly"
"Merck Molecular Activity Challenge","team-link team-player",1,"gggg","jeff","/users/62266/jeff"
"Merck Molecular Activity Challenge","team-link team-player",1,"gggg","Ruslan","/users/62726/ruslan"
"Merck Molecular Activity Challenge","team-link team-player",2,"DataRobot","Tom DeGodoy","/users/16192/tom-degodoy"
"Merck Molecular Activity Challenge","team-link team-player",2,"DataRobot","Xavier Conort","/xavierconort"
"Merck Molecular Activity Challenge","team-link team-player",2,"DataRobot","Jeremy Achin","/users/9441/jeremy-achin"
"Merck Molecular Activity Challenge","team-link team-player",3,".","Eu Jin Lok","/ejlok1"
"Merck Molecular Activity Challenge","team-link team-player",3,".","Zach","/zachmayer"
"Merck Molecular Activity Challenge","team-link team-player",3,".","Alexander Larko","/alexxanderlarko"
"West Nile Virus Prediction","team-link single-player",1,"Cardal","Cardal","/chaiml"
"West Nile Virus Prediction","team-link team-player",2,"Dmitry & Leustagos","Leustagos","/leustagos"
"West Nile Virus Prediction","team-link team-player",2,"Dmitry & Leustagos","Dmitry Efimov","/efimov"
"West Nile Virus Prediction","team-link single-player",3,"nhlx5haze","nhlx5haze","/nhlx5haze"
"Restaurant Revenue Prediction","team-link single-player",1,"Arsenal","Arsenal","/arsenal"
"Restaurant Revenue Prediction","team-link single-player",2,"Climent_Josep","Climent_Josep","/users/321915/climent-josep"
"Restaurant Revenue Prediction","team-link single-player",3,"OldSchool","OldSchool","/users/34298/gerold"
"Driver Telematics Analysis","team-link single-player",1,"Cardal","Cardal","/chaiml"
"Driver Telematics Analysis","team-link team-player",2,"Driving It","Scott H","/users/104302/scott-h"
"Driver Telematics Analysis","team-link team-player",2,"Driving It","Dr.Gigabit","/users/287432/dr-gigabit"
"Driver Telematics Analysis","team-link team-player",2,"Driving It","TheKeymaker","/thekeymaker"
"Driver Telematics Analysis","team-link single-player",3,"nhlx5haze","nhlx5haze","/nhlx5haze"
"Acquire Valued Shoppers Challenge","team-link team-player",1,"Marios & Gert","Μαριος Μιχαηλιδης KazAnova","/kazanova"
"Acquire Valued Shoppers Challenge","team-link team-player",1,"Marios & Gert","Gert","/gertjac"
"Acquire Valued Shoppers Challenge","team-link team-player",1,"Marios & Gert","yeticrab","/users/31633/yeticrab"
"Acquire Valued Shoppers Challenge","team-link team-player",2,"The Slippery Appraisals","Bluefool","/domcastro"
"Acquire Valued Shoppers Challenge","team-link team-player",2,"The Slippery Appraisals","Alexander Larko","/alexxanderlarko"
"Acquire Valued Shoppers Challenge","team-link team-player",2,"The Slippery Appraisals","Dmitry Larko","/dmitrylarko"
"Acquire Valued Shoppers Challenge","team-link team-player",2,"The Slippery Appraisals","Eu Jin Lok","/ejlok1"
"Acquire Valued Shoppers Challenge","team-link team-player",2,"The Slippery Appraisals","Zach","/zachmayer"
"Acquire Valued Shoppers Challenge","team-link single-player",3,"zzspar","zzspar","/udibr1"
"Liberty Mutual Group - Fire Peril Loss Cost","team-link team-player",1,"DataRobot","Xavier Conort","/xavierconort"
"Liberty Mutual Group - Fire Peril Loss Cost","team-link team-player",1,"DataRobot","Owen","/owenzhang1"
"Liberty Mutual Group - Fire Peril Loss Cost","team-link single-player",2,"Ivanhoe","Ivanhoe","/ivanhoe"
"Liberty Mutual Group - Fire Peril Loss Cost","team-link single-player",3,"barisumog","barisumog","/barisumog"
"American Epilepsy Society Seizure Prediction Challenge","team-link single-player",1,"Medrr","Medrr","/medial"
"American Epilepsy Society Seizure Prediction Challenge","team-link team-player",2,"QMSDP","Drew Abbot","/drewabbot"
"American Epilepsy Society Seizure Prediction Challenge","team-link team-player",2,"QMSDP","quang tieng","/users/207612/quang-tieng"
"American Epilepsy Society Seizure Prediction Challenge","team-link team-player",2,"QMSDP","Min Chen","/users/208949/min-chen"
"American Epilepsy Society Seizure Prediction Challenge","team-link team-player",2,"QMSDP","Simone","/users/229826/simone"
"American Epilepsy Society Seizure Prediction Challenge","team-link team-player",2,"QMSDP","Phillip Chilton Adkins","/phillipadkins"
"American Epilepsy Society Seizure Prediction Challenge","team-link single-player",3,"Birchwood","Birchwood","/jialunhe"
"Personalize Expedia Hotel Searches - ICDM 2013","team-link team-player",1,"commendo - part of Opera Solutions","Michael Jahrer","/mjahrer"
"Personalize Expedia Hotel Searches - ICDM 2013","team-link team-player",1,"commendo - part of Opera Solutions","AndreasToescher","/users/43867/andreastoescher"
"Personalize Expedia Hotel Searches - ICDM 2013","team-link single-player",2,"Owen","Owen","/owenzhang1"
"Personalize Expedia Hotel Searches - ICDM 2013","team-link single-player",3,"Jun Wang@UniGe","Jun Wang@UniGe","/users/124101/jun-wang"
"U.S. Census Return Rate Challenge","team-link single-player",1,"fodroczy","fodroczy","/users/60778/fodroczy"
"U.S. Census Return Rate Challenge","team-link single-player",2,"Not A US Citizen","Not A US Citizen","/users/2702/alec-stephenson"
"U.S. Census Return Rate Challenge","team-link single-player",3,"YetiMan","YetiMan","/yetiman"
"Belkin Energy Disaggregation Competition","team-link single-player",1,"jessica bombaz","jessica bombaz","/users/67252/jessica-bombaz"
"Belkin Energy Disaggregation Competition","team-link single-player",2,"Luis","Luis","/users/23759/luis-tandalla"
"Belkin Energy Disaggregation Competition","team-link team-player",3,"Titan","Noam Tene","/users/113421/noam-tene"
"Belkin Energy Disaggregation Competition","team-link team-player",3,"Titan","Yoyo They","/users/114469/yoyo-they"
"Belkin Energy Disaggregation Competition","team-link team-player",3,"Titan","ytene","/users/137014/ytene"
"GigaOM WordPress Challenge: Splunk Innovation Prospect","team-link single-player",1,"Carter","Carter","/cartersibley"
"GigaOM WordPress Challenge: Splunk Innovation Prospect","team-link single-player",2,"Olexandr Topchylo","Olexandr Topchylo","/topchylo"
"GigaOM WordPress Challenge: Splunk Innovation Prospect","team-link single-player",3,"student2012","student2012","/studentkgl2012"
"The Hunt for Prohibited Content","team-link team-player",1,"barisumog & Giulio","Giulio","/adjgiulio"
"The Hunt for Prohibited Content","team-link team-player",1,"barisumog & Giulio","barisumog","/barisumog"
"The Hunt for Prohibited Content","team-link team-player",2,"Mikhail & Dmitry","Mikhail Trofimov","/mikhailtrofimov"
"The Hunt for Prohibited Content","team-link team-player",2,"Mikhail & Dmitry","Dmitry Dryomov (YSDA)","/dremovd"
"The Hunt for Prohibited Content","team-link team-player",3,"Feng & Hang & Jeong-Yoon","Jeong-Yoon Lee","/jeongyoonlee"
"The Hunt for Prohibited Content","team-link team-player",3,"Feng & Hang & Jeong-Yoon","Hang","/soundwaveli00"
"The Hunt for Prohibited Content","team-link team-player",3,"Feng & Hang & Jeong-Yoon","Feng","/fengqi0423"
"Online Product Sales","team-link single-player",1,"falloutboy","falloutboy","/users/3021/peter-prettenhofer"
"Online Product Sales","team-link single-player",2,"Gxav","Gxav","/xavierconort"
"Online Product Sales","team-link team-player",3,"PlanetThanet & Stefan Henß & SirGuessalot","Jason Tigg","/users/7052/jason-tigg"
"Online Product Sales","team-link team-player",3,"PlanetThanet & Stefan Henß & SirGuessalot","Stefan Henß","/users/7117/stefan-hen"
"Online Product Sales","team-link team-player",3,"PlanetThanet & Stefan Henß & SirGuessalot","Momchil Georgiev","/sirguessalot"
"Observing Dark Worlds","team-link single-player",1,"Tim Salimans","Tim Salimans","/timsalimans"
"Observing Dark Worlds","team-link single-player",2,"Iain","Iain","/users/2476/iain"
"Observing Dark Worlds","team-link single-player",3,"AMPires","AMPires","/ampires"
"Predict Closed Questions on Stack Overflow","team-link single-player",1,"Malacka","Malacka","/melisgl"
"Predict Closed Questions on Stack Overflow","team-link team-player",2,"nbu","jsn13","/users/54892/jsn13"
"Predict Closed Questions on Stack Overflow","team-link team-player",2,"nbu","Leonid Kalmankin","/users/55080/leonid-kalmankin"
"Predict Closed Questions on Stack Overflow","team-link single-player",3,"James","James","/users/54493/james"
"Job Recommendation Challenge","team-link single-player",1,"PlanetThanet","PlanetThanet","/users/7052/jason-tigg"
"Job Recommendation Challenge","team-link single-player",2,"gaddawin","gaddawin","/users/11621/gaddawin"
"Job Recommendation Challenge","team-link team-player",3,"andrew","andrew","/users/37958/andrew"
"Job Recommendation Challenge","team-link team-player",3,"andrew","lisbethsalander","/users/56765/lisbethsalander"
"Predicting a Biological Response","team-link team-player",1,"Winter is Coming & Sergey","Jeremy Achin","/users/9441/jeremy-achin"
"Predicting a Biological Response","team-link team-player",1,"Winter is Coming & Sergey","Sergey Yurgenson","/ccccat"
"Predicting a Biological Response","team-link team-player",1,"Winter is Coming & Sergey","Tom DeGodoy","/users/16192/tom-degodoy"
"Predicting a Biological Response","team-link single-player",2,"seelary","seelary","/users/38703/mitrofan"
"Predicting a Biological Response","team-link single-player",3,"bluehat","bluehat","/users/33621/linus"
"Helping Santa\'s Helpers","team-link team-player",1,"Master Exploder","Marek Cygan","/marekcygan"
"Helping Santa\'s Helpers","team-link team-player",1,"Master Exploder","Marcin Mucha","/mmucha"
"Helping Santa\'s Helpers","team-link team-player",2,"Santa Express","Nana","/users/156404/nana"
"Helping Santa\'s Helpers","team-link team-player",2,"Santa Express","colun","/users/118083/colun"
"Helping Santa\'s Helpers","team-link team-player",3,"lzhexp & Kamil Dębowski","Kamil Dębowski","/errichto"
"Helping Santa\'s Helpers","team-link team-player",3,"lzhexp & Kamil Dębowski","lzhexp","/users/103273/lzhexp"
"Search Results Relevance","team-link single-player",1,"Chenglong Chen","Chenglong Chen","/chenglongchen"
"Search Results Relevance","team-link team-player",2,"Mikhail & Stanislav & Dmitry","Mikhail Trofimov","/mikhailtrofimov"
"Search Results Relevance","team-link team-player",2,"Mikhail & Stanislav & Dmitry","Stanislav Semenov","/stasg7"
"Search Results Relevance","team-link team-player",2,"Mikhail & Stanislav & Dmitry","utility","/utility"
"Search Results Relevance","team-link team-player",3,"Quartet","madcap","/madcap"
"Search Results Relevance","team-link team-player",3,"Quartet","Dowakin","/dowakin"
"Search Results Relevance","team-link team-player",3,"Quartet","Alejandro Simkievich","/asimkievich"
"Search Results Relevance","team-link team-player",3,"Quartet","Sergio Gámez","/sgamez"
"Avito Context Ad Clicks","team-link single-player",1,"Owen","Owen","/owenzhang1"
"Avito Context Ad Clicks","team-link single-player",2,"Gzs_iceberg","Gzs_iceberg","/gzsiceberg"
"Avito Context Ad Clicks","team-link team-player",3,"Dmitry & Leustagos","Leustagos","/leustagos"
"Avito Context Ad Clicks","team-link team-player",3,"Dmitry & Leustagos","Dmitry Efimov","/efimov"
"The Big Data Combine Engineered by BattleFin","team-link single-player",1,"BreakfastPirate","BreakfastPirate","/users/9766/breakfastpirate"
"The Big Data Combine Engineered by BattleFin","team-link single-player",2,"SY","SY","/ccccat"
"The Big Data Combine Engineered by BattleFin","team-link single-player",3,"Ed Ramsden","Ed Ramsden","/users/1553/ed-ramsden"
"Benchmark Bond Trade Price Challenge","team-link team-player",1,"upbeat","infty","/users/36878/infty"
"Benchmark Bond Trade Price Challenge","team-link team-player",1,"upbeat","random modeler","/users/36885/random-modeler"
"Benchmark Bond Trade Price Challenge","team-link team-player",2,"S&B500","Bruce Cragin","/bcragin"
"Benchmark Bond Trade Price Challenge","team-link team-player",2,"S&B500","Sergey Yurgenson","/ccccat"
"Benchmark Bond Trade Price Challenge","team-link team-player",3,"VikP & Sergey","Sergey","/users/3876/sergey"
"Benchmark Bond Trade Price Challenge","team-link team-player",3,"VikP & Sergey","Vik Paruchuri","/vikpar"
"Galaxy Zoo - The Galaxy Challenge","team-link single-player",1,"sedielem","sedielem","/sedielem"
"Galaxy Zoo - The Galaxy Challenge","team-link single-player",2,"Maxim Milakov","Maxim Milakov","/milakov"
"Galaxy Zoo - The Galaxy Challenge","team-link team-player",3,"6789","tund","/users/41096/tund"
"Galaxy Zoo - The Galaxy Challenge","team-link team-player",3,"6789","Truyen Tran","/truyen"
"Display Advertising Challenge","team-link team-player",1,"3 Idiots","guestwalk","/users/78307/guestwalk"
"Display Advertising Challenge","team-link team-player",1,"3 Idiots","mandora","/users/95300/mandora"
"Display Advertising Challenge","team-link team-player",1,"3 Idiots","yolicat","/mengmengyong"
"Display Advertising Challenge","team-link team-player",2,"Michael Jahrer and Jeong-Yoon Lee","Michael Jahrer","/mjahrer"
"Display Advertising Challenge","team-link team-player",2,"Michael Jahrer and Jeong-Yoon Lee","Jeong-Yoon Lee","/jeongyoonlee"
"Display Advertising Challenge","team-link single-player",3,"beile","beile","/users/41275/guocong-song"
"Microsoft Malware Classification Challenge (BIG 2015)","team-link team-player",1,"say NOOOOO to overfittttting","Little Boat","/xiaozhouwang"
"Microsoft Malware Classification Challenge (BIG 2015)","team-link team-player",1,"say NOOOOO to overfittttting","rcarson","/jiweiliu"
"Microsoft Malware Classification Challenge (BIG 2015)","team-link team-player",1,"say NOOOOO to overfittttting","Xueer Chen","/xueerchen"
"Microsoft Malware Classification Challenge (BIG 2015)","team-link team-player",2,"Marios & Gert","Gert","/gertjac"
"Microsoft Malware Classification Challenge (BIG 2015)","team-link team-player",2,"Marios & Gert","Μαριος Μιχαηλιδης KazAnova","/kazanova"
"Microsoft Malware Classification Challenge (BIG 2015)","team-link team-player",3,"Mikhail & Dmitry & Stanislav","Mikhail Trofimov","/mikhailtrofimov"
"Microsoft Malware Classification Challenge (BIG 2015)","team-link team-player",3,"Mikhail & Dmitry & Stanislav","Dmitry Ulyanov","/dulyanov"
"Microsoft Malware Classification Challenge (BIG 2015)","team-link team-player",3,"Mikhail & Dmitry & Stanislav","Stanislav Semenov","/stasg7"
"Click-Through Rate Prediction","team-link team-player",1,"4 Idiots","guestwalk","/users/78307/guestwalk"
"Click-Through Rate Prediction","team-link team-player",1,"4 Idiots","Michael Jahrer","/mjahrer"
"Click-Through Rate Prediction","team-link team-player",1,"4 Idiots","yolicat","/mengmengyong"
"Click-Through Rate Prediction","team-link team-player",1,"4 Idiots","mandora","/users/95300/mandora"
"Click-Through Rate Prediction","team-link single-player",2,"Owen","Owen","/owenzhang1"
"Click-Through Rate Prediction","team-link team-player",3,"Random Walker","infinitezxc","/infinite"
"Click-Through Rate Prediction","team-link team-player",3,"Random Walker","eureka","/pengyan"
"March Machine Learning Mania 2015","team-link single-player",1,"Zach B","Zach B","/users/311573/zdb-88"
"March Machine Learning Mania 2015","team-link single-player",2,"Monte McNair","Monte McNair","/users/176110/monte-mcnair"
"March Machine Learning Mania 2015","team-link single-player",3,"PookieBearNecessities","PookieBearNecessities","/users/312401/pookiebearnecessities"
"March Machine Learning Mania","team-link team-player",1,"One shining MGF","statsinthewild","/statsinthewild"
"March Machine Learning Mania","team-link team-player",1,"One shining MGF","Michael Lopez","/users/176222/michael-lopez"
"March Machine Learning Mania","team-link single-player",2,"Jason_ATX","Jason_ATX","/jasonsumpter"
"March Machine Learning Mania","team-link single-player",3,"zachtrexler","zachtrexler","/users/173509/zachtrexler"
"Higgs Boson Machine Learning Challenge","team-link single-player",1,"Gábor Melis","Gábor Melis","/melisgl"
"Higgs Boson Machine Learning Challenge","team-link single-player",2,"Tim Salimans","Tim Salimans","/timsalimans"
"Higgs Boson Machine Learning Challenge","team-link single-player",3,"nhlx5haze","nhlx5haze","/nhlx5haze"
"EMC Israel Data Science Challenge","team-link single-player",1,"Mike","Mike","/users/25508/pankaj-mishra"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Jure Zbontar","/users/835/jure-zbontar"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Marinka Zitnik","/users/18347/marinka-zitnik"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Anže Kravanja","/users/27300/an-e-kravanja"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Ernest Belicic","/users/51870/ernest-belicic"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Urska Kosec","/users/28004/urska-kosec"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","MATEVŽ ČERNE","/users/49537/matev-erne"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Gregor Časar","/users/50836/gregor-asar"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Matic Plešec","/users/50873/matic-ple-ec"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Urban Škudnik","/users/50833/urban-kudnik"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Nejc Štebe","/users/49894/nejc-tebe"
"EMC Israel Data Science Challenge","team-link team-player",2,"ULjubljana","Marko Lalović","/users/50838/marko-lalovi"
"EMC Israel Data Science Challenge","team-link team-player",3,"ApesTeam","FRP","/users/46275/frp"
"EMC Israel Data Science Challenge","team-link team-player",3,"ApesTeam","Emilio G. Ortiz-García","/users/46205/emilio-g-ortiz-garc-a"
"EMC Israel Data Science Challenge","team-link team-player",3,"ApesTeam","LMG","/users/46383/lmg"
"EMC Israel Data Science Challenge","team-link team-player",3,"ApesTeam","JJ-ATRG","/users/48145/jj-atrg"
"EMC Israel Data Science Challenge","team-link team-player",3,"ApesTeam","Roberto","/robertod"
"Practice Fusion Diabetes Classification","team-link single-player",1,"J.A. Guerrero","J.A. Guerrero","/blindape"
"Practice Fusion Diabetes Classification","team-link single-player",2,"__mtb__","__mtb__","/users/26767/mtb"
"Practice Fusion Diabetes Classification","team-link single-player",3,"An apple a day","An apple a day","/srgodbole"
"Detecting Insults in Social Commentary","team-link single-player",1,"Vivek Sharma","Vivek Sharma","/users/5048/vivek-sharma"
"Detecting Insults in Social Commentary","team-link single-player",2,"tuzzeg","tuzzeg","/tuzzeg"
"Detecting Insults in Social Commentary","team-link single-player",3,"Andrei Olariu","Andrei Olariu","/aolariu"
"EMI Music Data Science Hackathon - July 21st - 24 hours","team-link team-player",1,"Shanda Innovations","Yunwen Chen","/users/35988/yunwen-chen"
"EMI Music Data Science Hackathon - July 21st - 24 hours","team-link team-player",1,"Shanda Innovations","Lu Yao","/users/40067/lu-yao"
"EMI Music Data Science Hackathon - July 21st - 24 hours","team-link team-player",1,"Shanda Innovations","Yingwei Xin","/users/43165/yingwei-xin"
"EMI Music Data Science Hackathon - July 21st - 24 hours","team-link team-player",1,"Shanda Innovations","Daqi Ji","/users/43166/daqi-ji"
"EMI Music Data Science Hackathon - July 21st - 24 hours","team-link team-player",1,"Shanda Innovations","wgwang","/users/43172/wgwang"
"EMI Music Data Science Hackathon - July 21st - 24 hours","team-link team-player",1,"Shanda Innovations","Winterfell","/fancyspeed"
"EMI Music Data Science Hackathon - July 21st - 24 hours","team-link single-player",2,"lns","lns","/users/33621/linus"
"EMI Music Data Science Hackathon - July 21st - 24 hours","team-link single-player",3,"Martin","Martin","/users/10748/martin-o-leary"
"CPROD1: Consumer PRODucts contest #1","team-link team-player",1,"ISSSID","Ronaldosen","/users/32352/ronaldosen"
"CPROD1: Consumer PRODucts contest #1","team-link team-player",1,"ISSSID","FAndy","/users/33620/fandy"
"CPROD1: Consumer PRODucts contest #1","team-link single-player",2,"Olexandr Topchylo","Olexandr Topchylo","/topchylo"
"CPROD1: Consumer PRODucts contest #1","team-link single-player",3,"8000","8000","/lukasz8000"
"Raising Money to Fund an Organizational Mission","team-link single-player",1,"Richard Courtheoux","Richard Courtheoux","/precmarket"
"Raising Money to Fund an Organizational Mission","team-link single-player",2,"erdman","erdman","/users/13518/travis-erdman"
"Raising Money to Fund an Organizational Mission","team-link single-player",3,"PlanetThanet","PlanetThanet","/users/7052/jason-tigg"
"CHALEARN Gesture Challenge 2","team-link single-player",1,"alfnie","alfnie","/alfnie"
"CHALEARN Gesture Challenge 2","team-link single-player",2,"Joewan","Joewan","/users/48323/joewan"
"CHALEARN Gesture Challenge 2","team-link single-player",3,"Wayne Zhang","Wayne Zhang","/waynezhang"
"Wikipedia\'s Participation Challenge","team-link team-player",1,"prognoZit","Benjamin Roth","/users/14165/benjamin-roth"
"Wikipedia\'s Participation Challenge","team-link team-player",1,"prognoZit","Frido","/users/16537/frido"
"Wikipedia\'s Participation Challenge","team-link single-player",2,"Ernest Shackleton","Ernest Shackleton","/users/13240/keith-t-herring"
"Wikipedia\'s Participation Challenge","team-link single-player",3,"zeditor","zeditor","/users/8267/dell-zhang"
"Allstate Claim Prediction Challenge","team-link single-player",1,"Matt C","Matt C","/users/13372/matthew-carle"
"Allstate Claim Prediction Challenge","team-link single-player",2,"Owen","Owen","/owenzhang1"
"Allstate Claim Prediction Challenge","team-link single-player",3,"PlanetThanet","PlanetThanet","/users/7052/jason-tigg"
"dunnhumby\'s Shopper Challenge","team-link single-player",1,"D\'yakonov Alexander (MSU, Moscow, Russia)","D\'yakonov Alexander (MSU, Moscow, Russia)","/dyakonov"
"dunnhumby\'s Shopper Challenge","team-link single-player",2,"NSchneider","NSchneider","/users/7657/neil-schneider"
"dunnhumby\'s Shopper Challenge","team-link single-player",3,"Ben Hamner","Ben Hamner","/benhamner"
"Don\'t Get Kicked!","team-link team-player",1,"Sollers & Gxav","Marcin Pionnier","/users/2827/marcin-pionnier"
"Don\'t Get Kicked!","team-link team-player",1,"Sollers & Gxav","Xavier Conort","/xavierconort"
"Don\'t Get Kicked!","team-link team-player",2,"Old Dogs With New Tricks","David J. Slate","/dslate"
"Don\'t Get Kicked!","team-link team-player",2,"Old Dogs With New Tricks","Peter W Frey","/pwfrey42"
"Don\'t Get Kicked!","team-link single-player",3,"vsu","vsu","/users/1664/vsu"
"Algorithmic Trading Challenge","team-link single-player",1,"Ildefons Magrans","Ildefons Magrans","/ildefons"
"Algorithmic Trading Challenge","team-link single-player",2,"alegro","alegro","/users/2820/alegro"
"Algorithmic Trading Challenge","team-link single-player",3,"vsh","vsh","/users/5048/vivek-sharma"
"CHALEARN Gesture Challenge","team-link single-player",1,"alfnie","alfnie","/alfnie"
"CHALEARN Gesture Challenge","team-link team-player",2,"Pennect","Yu Luo","/users/30351/yu-luo"
"CHALEARN Gesture Challenge","team-link team-player",2,"Pennect","David Weiss","/users/9082/david-weiss"
"CHALEARN Gesture Challenge","team-link team-player",2,"Pennect","Chushi","/users/35481/chushi"
"CHALEARN Gesture Challenge","team-link single-player",3,"One Million Monkeys","One Million Monkeys","/onemillionmonkeys"
"RTA Freeway Travel Time Prediction","team-link team-player",1,"Team Irazu","Guido Matias Cortes","/users/4426/guido-matias-cortes"
"RTA Freeway Travel Time Prediction","team-link team-player",1,"Team Irazu","Jose","/users/4410/jose"
"RTA Freeway Travel Time Prediction","team-link single-player",2,"Mooma","Mooma","/ccccat"
"RTA Freeway Travel Time Prediction","team-link single-player",3,"SuperCow","SuperCow","/users/5596/alisson-azzolini"
"Deloitte/FIDE Chess Rating Challenge","team-link single-player",1,"Tim Salimans","Tim Salimans","/timsalimans"
"Deloitte/FIDE Chess Rating Challenge","team-link single-player",2,"Shang Tsung","Shang Tsung","/users/6019/sami"
"Deloitte/FIDE Chess Rating Challenge","team-link single-player",3,"George","George","/users/9684/george"
"Loan Default Prediction - Imperial College London","team-link single-player",1,"Josef Feigl","Josef Feigl","/joseffeigl"
"Loan Default Prediction - Imperial College London","team-link single-player",2,"HelloWorld","HelloWorld","/junchaolyu"
"Loan Default Prediction - Imperial College London","team-link single-player",3,"Beile","Beile","/users/41275/guocong-song"
"Packing Santa\'s Sleigh","team-link team-player",1,"Master Exploder","Marcin Mucha","/mmucha"
"Packing Santa\'s Sleigh","team-link team-player",1,"Master Exploder","Marek Cygan","/marekcygan"
"Packing Santa\'s Sleigh","team-link single-player",2,"Alfonso Nieto-Castanon","Alfonso Nieto-Castanon","/alfnie"
"Packing Santa\'s Sleigh","team-link single-player",3,"wleite","wleite","/users/76482/wleite"
"Cause-effect pairs","team-link team-player",1,"ProtoML","Dee5","/diogo149"
"Cause-effect pairs","team-link team-player",1,"ProtoML","[◈▃◈]","/users/114051/-"
"Cause-effect pairs","team-link team-player",1,"ProtoML","askii93","/users/106286/askii93"
"Cause-effect pairs","team-link single-player",2,"jarfo","jarfo","/users/95601/jos-a-r-fonollosa"
"Cause-effect pairs","team-link team-player",3,"HiDLoN","Sitmo","/users/28261/sitmo"
"Cause-effect pairs","team-link team-player",3,"HiDLoN","WorkingKnowledge","/users/41692/workingknowledge"
"Blue Book for Bulldozers","team-link team-player",1,"Leustagos & Titericz","Leustagos","/leustagos"
"Blue Book for Bulldozers","team-link team-player",1,"Leustagos & Titericz","Gilberto Titericz Junior","/titericz"
"Blue Book for Bulldozers","team-link single-player",2,"Alessandro Mariani","Alessandro Mariani","/alzmcr"
"Blue Book for Bulldozers","team-link single-player",3,"An apple a day","An apple a day","/srgodbole"
"The Marinexplore and Cornell University Whale Detection Challenge","team-link team-player",1,"SluiceBox","Nick Kridler","/users/7947/nick-kridler"
"The Marinexplore and Cornell University Whale Detection Challenge","team-link team-player",1,"SluiceBox","Scott Dobson","/users/5978/scott-dobson"
"The Marinexplore and Cornell University Whale Detection Challenge","team-link single-player",2,"alfnie","alfnie","/alfnie"
"The Marinexplore and Cornell University Whale Detection Challenge","team-link team-player",3,"RBM","Charlie Tang","/users/2412/charlie-tang"
"The Marinexplore and Cornell University Whale Detection Challenge","team-link team-player",3,"RBM","Navdeep Jaitly","/users/61041/navdeep-jaitly"
"The Marinexplore and Cornell University Whale Detection Challenge","team-link team-player",3,"RBM","ShallowNet","/users/93280/shallownet"
"Multi-modal Gesture Recognition","team-link team-player",1,"iva.mm","Jiaxiang Wu","/users/76636/jiaxiang-wu"
"Multi-modal Gesture Recognition","team-link team-player",1,"iva.mm","Jian Cheng","/users/118055/jian-cheng"
"Multi-modal Gesture Recognition","team-link team-player",1,"iva.mm","cyzhao","/users/118058/cyzhao"
"Multi-modal Gesture Recognition","team-link team-player",1,"iva.mm","Hanqing Lu","/users/118056/hanqing-lu"
"Multi-modal Gesture Recognition","team-link single-player",2,"wweight","wweight","/rkeisler"
"Multi-modal Gesture Recognition","team-link team-player",3,"MmM","LI Wei","/weilinear"
"Multi-modal Gesture Recognition","team-link team-player",3,"MmM","Limin Wang","/users/116851/limin-wang"
"Otto Group Product Classification Challenge","team-link team-player",1,"Gilberto Titericz & Stanislav Semenov","Gilberto Titericz Junior","/titericz"
"Otto Group Product Classification Challenge","team-link team-player",1,"Gilberto Titericz & Stanislav Semenov","Stanislav Semenov","/stasg7"
"Otto Group Product Classification Challenge","team-link single-player",2,"¯\\_(ツ)_/¯","¯\\_(ツ)_/¯","/aguschin"
"Otto Group Product Classification Challenge","team-link team-player",3,"i dont know","Abhishek","/abhishek"
"Otto Group Product Classification Challenge","team-link team-player",3,"i dont know","Michael Jahrer","/mjahrer"
"Otto Group Product Classification Challenge","team-link team-player",3,"i dont know","Jeong-Yoon Lee","/jeongyoonlee"
"Personalized Web Search Challenge","team-link single-player",1,"pampampampam (ooc)","pampampampam (ooc)","/users/133646/pampampampam"
"Personalized Web Search Challenge","team-link team-player",2,"Dataiku Data Science Studio","Paul Masurel","/fulmicoton"
"Personalized Web Search Challenge","team-link team-player",2,"Dataiku Data Science Studio","Matt Sco","/mattsco"
"Personalized Web Search Challenge","team-link team-player",2,"Dataiku Data Science Studio","Kenji Lefèvre","/users/111271/kenji-lef-vre"
"Personalized Web Search Challenge","team-link team-player",2,"Dataiku Data Science Studio","Christophe Bourguignat","/cbourguignat"
"Personalized Web Search Challenge","team-link single-player",3,"LR","LR","/users/41275/guocong-song"
"PAKDD 2014 - ASUS Malfunctional Components Prediction","team-link single-player",1,"Herra Huu","Herra Huu","/herrahuu"
"PAKDD 2014 - ASUS Malfunctional Components Prediction","team-link single-player",2,"eluk","eluk","/users/114594/eluk"
"PAKDD 2014 - ASUS Malfunctional Components Prediction","team-link single-player",3,"Shize Su","Shize Su","/sushize"
"UPenn and Mayo Clinic\'s Seizure Detection Challenge","team-link single-player",1,"Michael Hills","Michael Hills","/users/110805/michael-hills"
"UPenn and Mayo Clinic\'s Seizure Detection Challenge","team-link team-player",2,"Olson and Mingle","emolson","/users/165406/emolson"
"UPenn and Mayo Clinic\'s Seizure Detection Challenge","team-link team-player",2,"Olson and Mingle","Damian Mingle","/damianmingle"
"UPenn and Mayo Clinic\'s Seizure Detection Challenge","team-link team-player",3,"cdipsters","Alex","/users/215872/alex"
"UPenn and Mayo Clinic\'s Seizure Detection Challenge","team-link team-player",3,"cdipsters","ishan","/users/215598/ishan"
"UPenn and Mayo Clinic\'s Seizure Detection Challenge","team-link team-player",3,"cdipsters","Nathan Moore","/users/215868/nathan-moore"
"Africa Soil Property Prediction Challenge ","team-link single-player",1,"Yasser Tabandeh","Yasser Tabandeh","/yassertabandeh"
"Africa Soil Property Prediction Challenge ","team-link single-player",2,"Charly B.","Charly B.","/cbitton"
"Africa Soil Property Prediction Challenge ","team-link team-player",3,"CodiLime.com","robibok","/robibok"
"Africa Soil Property Prediction Challenge ","team-link team-player",3,"CodiLime.com","MillCheck","/datarat"
"Africa Soil Property Prediction Challenge ","team-link team-player",3,"CodiLime.com","marian","/marian"
"Africa Soil Property Prediction Challenge ","team-link team-player",3,"CodiLime.com","Iwan Groźny","/users/212902/iwan-gro-ny"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","Tianqi Chen","/tqchen"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","Linpeng Tang","/users/33383/linpeng-tang"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","lqhl","/users/33381/lqhl"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","yepyao","/users/43948/yepyao"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","Sain","/users/43949/sain"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","phoneix","/users/33580/phoneix"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","gameboy","/users/43953/gameboy"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","a9108","/cxz2004"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","jzhsh1735","/users/36550/jzhsh1735"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","jackcc","/users/36118/jackcc"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","_bzd","/users/43976/bzd"
"KDD Cup 2012, Track 1","team-link team-player",1,"ACMClass@SJTU","Bird","/users/43977/bird"
"KDD Cup 2012, Track 1","team-link team-player",2,"Shanda Innovations","Yunwen Chen","/users/35988/yunwen-chen"
"KDD Cup 2012, Track 1","team-link team-player",2,"Shanda Innovations","Yingwei Xin","/users/43165/yingwei-xin"
"KDD Cup 2012, Track 1","team-link team-player",2,"Shanda Innovations","Lu Yao","/users/43168/lu-yao"
"KDD Cup 2012, Track 1","team-link team-player",2,"Shanda Innovations","Yi Zou","/users/43171/yi-zou"
"KDD Cup 2012, Track 1","team-link team-player",2,"Shanda Innovations","Daqi Ji","/users/43166/daqi-ji"
"KDD Cup 2012, Track 1","team-link team-player",2,"Shanda Innovations","Winterfell","/fancyspeed"
"KDD Cup 2012, Track 1","team-link team-player",2,"Shanda Innovations","wgwang","/users/43172/wgwang"
"KDD Cup 2012, Track 1","team-link team-player",3,"SYSU_Wargreymon","Yilin Cai","/users/34623/yilin-cai"
"KDD Cup 2012, Track 1","team-link team-player",3,"SYSU_Wargreymon","Yubin Xie","/users/34652/yubin-xie"
"KDD Cup 2012, Track 1","team-link team-player",3,"SYSU_Wargreymon","Yuanxun Chen","/users/33477/yuanxun-chen"
"KDD Cup 2012, Track 1","team-link team-player",3,"SYSU_Wargreymon","Arkchar","/users/35717/arkchar"
"KDD Cup 2012, Track 1","team-link team-player",3,"SYSU_Wargreymon","SongshanGuo","/users/44637/songshanguo"
"KDD Cup 2012, Track 1","team-link team-player",3,"SYSU_Wargreymon","XiaomingLiu","/users/44639/xiaomingliu"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","squirrel","/users/42831/squirrel"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","Potato","/users/6133/potato"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","KW Wu","/users/42832/kw-wu"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","hypertext","/users/43882/hypertext"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","msla","/users/43883/msla"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","ddoo","/users/33583/ddoo"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","negocylg","/users/43886/negocylg"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","FLash","/users/43884/flash"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","InTheBamboo","/users/43890/inthebamboo"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","wolala","/lintseju"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","noidea","/users/43895/noidea"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","BigOld","/users/43896/bigold"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","awdqse","/users/43918/awdqse"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","FattyBetty","/users/33968/fattybetty"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","leepei","/users/33495/leepei"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","totu","/users/43905/totu"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","smile","/users/43911/smile"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","abc123","/users/43889/abc123"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","Fluttershy","/users/43943/fluttershy"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","Pernghwa","/users/43947/pernghwa"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","raindog","/users/43966/raindog"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","rvcl","/users/43978/rvcl"
"KDD Cup 2012, Track 2","team-link team-player",1,"Catch up @ National Taiwan University","plus","/users/33582/plus"
"KDD Cup 2012, Track 2","team-link team-player",2,"Opera Solutions","Jeong-Yoon Lee","/jeongyoonlee"
"KDD Cup 2012, Track 2","team-link team-player",2,"Opera Solutions","Michael Jahrer","/mjahrer"
"KDD Cup 2012, Track 2","team-link team-player",2,"Opera Solutions","Hang Zhang","/users/43926/hang-zhang"
"KDD Cup 2012, Track 2","team-link team-player",2,"Opera Solutions","blednotik","/users/25442/blednotik"
"KDD Cup 2012, Track 2","team-link team-player",2,"Opera Solutions","AndreasToescher","/users/43867/andreastoescher"
"KDD Cup 2012, Track 2","team-link team-player",2,"Opera Solutions","Liang Sun","/users/19557/liang-sun"
"KDD Cup 2012, Track 2","team-link team-player",2,"Opera Solutions","Luv2av8","/users/7527/luv2av8"
"KDD Cup 2012, Track 2","team-link team-player",2,"Opera Solutions","Lei Shi","/users/16152/lei-shi"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","char","/users/44275/char"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","kuskus","/users/44274/kuskus"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","bnnkong2099","/users/44278/bnnkong2099"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","unnamesir","/users/44323/unnamesir"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","nscc","/users/44329/nscc"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","double","/users/44334/double"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","ycog","/users/44303/ycog"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","Wu Liang","/users/44373/wu-liang"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","jaent","/users/44336/jaent"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","WaterFish","/users/44346/waterfish"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","xxx","/users/44482/xxx"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","ssll","/users/44483/ssll"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","beingcel002","/users/44454/beingcel002"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","HelloWorld","/users/43781/helloworld"
"KDD Cup 2012, Track 2","team-link team-player",3,"Chinese Academy of Sciences","zgb_iva","/users/44484/zgb-iva"
"Global Energy Forecasting Competition 2012 - Load Forecasting","team-link single-player",1,"Tiberius Data Mining","Tiberius Data Mining","/users/1335/sali-mali"
"Global Energy Forecasting Competition 2012 - Load Forecasting","team-link team-player",2,"CountingLab","ColinAtCountingLab","/users/52187/colinatcountinglab"
"Global Energy Forecasting Competition 2012 - Load Forecasting","team-link team-player",2,"CountingLab","Billiejoe","/users/64542/billiejoe"
"Global Energy Forecasting Competition 2012 - Load Forecasting","team-link single-player",3,"James Lloyd","James Lloyd","/users/50827/james-lloyd"
"Global Energy Forecasting Competition 2012 - Wind Forecasting","team-link single-player",1,"Leustagos","Leustagos","/leustagos"
"Global Energy Forecasting Competition 2012 - Wind Forecasting","team-link single-player",2,"DuckTile","DuckTile","/ducktile"
"Global Energy Forecasting Competition 2012 - Wind Forecasting","team-link single-player",3,"Gilberto Titericz Jr","Gilberto Titericz Jr","/titericz"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","BigOld","/users/43896/bigold"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","SYY","/users/97203/syy"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","JMY!!","/users/97201/jmy"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","Hitachi","/users/95463/hitachi"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","Arc","/users/97182/arc"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","hahaha","/users/97220/hahaha"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","yolicat","/mengmengyong"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","Sammy","/users/97238/sammy"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","Shan-Wei Lin","/b99902023"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","acacam","/users/97248/acacam"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","October","/users/97342/october"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","rockerman","/users/97360/rockerman"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","r44","/users/97366/r44"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","ej0cl6","/ej0cl6"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","kerker","/users/94750/kerker"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","whengraduate","/users/97420/whengraduate"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","Guava","/users/97477/guava"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","guestwalk","/users/78307/guestwalk"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","mandora","/users/95300/mandora"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","KennyW","/kennyw"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","FishTung","/users/98112/fishtung"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","cjlin","/users/105017/cjlin"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","hypertext","/users/43882/hypertext"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",1,"Algorithm @ National Taiwan University","msla","/users/43883/msla"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",2,"Dmitry&Leustagos&BS Man","Dmitry Efimov","/efimov"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",2,"Dmitry&Leustagos&BS Man","Leustagos","/leustagos"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link team-player",2,"Dmitry&Leustagos&BS Man","Ben S","/bensolucky"
"KDD Cup 2013 - Author-Paper Identification Challenge (Track 1)","team-link single-player",3,"mb74","mb74","/xingzhao"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","BigOld","/users/43896/bigold"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","SYY","/users/97203/syy"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","JMY!!","/users/97201/jmy"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","Hitachi","/users/95463/hitachi"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","Arc","/users/97182/arc"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","hahaha","/users/97220/hahaha"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","yolicat","/mengmengyong"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","Sammy","/users/97238/sammy"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","Shan-Wei Lin","/b99902023"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","acacam","/users/97248/acacam"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","October","/users/97342/october"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","rockerman","/users/97360/rockerman"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","r44","/users/97366/r44"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","ej0cl6","/ej0cl6"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","kerker","/users/94750/kerker"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","Guava","/users/97477/guava"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","whengraduate","/users/97420/whengraduate"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","guestwalk","/users/78307/guestwalk"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","mandora","/users/95300/mandora"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","KennyW","/kennyw"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","FishTung","/users/98112/fishtung"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","msla","/users/43883/msla"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","cjlin","/users/105017/cjlin"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",1,"Algorithm @ National Taiwan University","hypertext","/users/43882/hypertext"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",2,"SmallData@UIUC","Jialu","/users/98336/jialu"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",2,"SmallData@UIUC","Tobias Lei","/users/96878/tobias-lei"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",2,"SmallData@UIUC","TooManyBugs","/users/102936/toomanybugs"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",2,"SmallData@UIUC","Jeffrey Yufei Liu","/users/1881/jeffrey-yufei-liu"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link team-player",2,"SmallData@UIUC","Jiawei Han","/users/104940/jiawei-han"
"KDD Cup 2013 - Author Disambiguation Challenge (Track 2)","team-link single-player",3,"柳景明","柳景明","/hustmonk"
"EMC Data Science Global Hackathon (Air Quality Prediction)","team-link single-player",1,"Ben Hamner (Kaggle - Ineligible for Prizes)","Ben Hamner (Kaggle - Ineligible for Prizes)","/benhamner"
"EMC Data Science Global Hackathon (Air Quality Prediction)","team-link single-player",2,"James Petterson","James Petterson","/jpetterson"
"EMC Data Science Global Hackathon (Air Quality Prediction)","team-link team-player",3,"feeling_unlucky","roobs","/users/5218/roobs"
"EMC Data Science Global Hackathon (Air Quality Prediction)","team-link team-player",3,"feeling_unlucky","ThomM","/users/25743/thomm"
"EMC Data Science Global Hackathon (Air Quality Prediction)","team-link team-player",3,"feeling_unlucky","Mike","/users/41367/mike"
"Job Salary Prediction","team-link single-player",1,"lazylearner","lazylearner","/users/5983/lazylearner"
"Job Salary Prediction","team-link single-player",2,"Vlado Boza","Vlado Boza","/usamec"
"Job Salary Prediction","team-link single-player",3,"LR","LR","/users/41275/guocong-song"
"dunnhumby & hack/reduce Product Launch Challenge","team-link single-player",1,"Jaysen Gillespie","Jaysen Gillespie","/users/4717/jaysen-gillespie"
"dunnhumby & hack/reduce Product Launch Challenge","team-link single-player",2,"n_m","n_m","/naokazumizuta"
"dunnhumby & hack/reduce Product Launch Challenge","team-link single-player",3,"Dmitry Efimov","Dmitry Efimov","/efimov"
"StumbleUpon Evergreen Classification Challenge","team-link single-player",1,"fchollet","fchollet","/fchollet"
"StumbleUpon Evergreen Classification Challenge","team-link single-player",2,"Maarten Bosma","Maarten Bosma","/ma2rten"
"StumbleUpon Evergreen Classification Challenge","team-link single-player",3,"michaelp","michaelp","/users/112986/michaelp"
"Accelerometer Biometric Competition","team-link single-player",1,"gaddawin","gaddawin","/users/11621/gaddawin"
"Accelerometer Biometric Competition","team-link single-player",2,"Solórzano","Solórzano","/solorzano"
"Accelerometer Biometric Competition","team-link single-player",3,"Target Leak Model","Target Leak Model","/users/30481/r0u1i"
"Amazon.com - Employee Access Challenge","team-link team-player",1,"Paul Duan & BS Man","Paul Duan","/users/44623/paul-duan"
"Amazon.com - Employee Access Challenge","team-link team-player",1,"Paul Duan & BS Man","Ben S","/bensolucky"
"Amazon.com - Employee Access Challenge","team-link single-player",2,"Owen Zhang","Owen Zhang","/owenzhang1"
"Amazon.com - Employee Access Challenge","team-link team-player",3,"Dmitry&Leustagos","Dmitry Efimov","/efimov"
"Amazon.com - Employee Access Challenge","team-link team-player",3,"Dmitry&Leustagos","Leustagos","/leustagos"
"DecMeg2014 - Decoding the Human Brain","team-link single-player",1,"Alexandre Barachant","Alexandre Barachant","/alexandrebarachant"
"DecMeg2014 - Decoding the Human Brain","team-link team-player",2,"Heikki Huttunen","Heikki Huttunen","/mahehu"
"DecMeg2014 - Decoding the Human Brain","team-link team-player",2,"Heikki Huttunen","Oguzhan Gencoglu","/ogencoglu"
"DecMeg2014 - Decoding the Human Brain","team-link team-player",2,"Heikki Huttunen","johannes","/users/208710/johannes"
"DecMeg2014 - Decoding the Human Brain","team-link team-player",2,"Heikki Huttunen","Teemu Vartiainen","/users/210842/teemu-vartiainen"
"DecMeg2014 - Decoding the Human Brain","team-link single-player",3,"Nathan Hammes","Nathan Hammes","/users/169446/nathan-hammes"
"Give Me Some Credit","team-link team-player",1,"Perfect Storm","Alec Stephenson","/users/2702/alec-stephenson"
"Give Me Some Credit","team-link team-player",1,"Perfect Storm","Eu Jin Lok","/ejlok1"
"Give Me Some Credit","team-link team-player",1,"Perfect Storm","Nathaniel Ramm","/rambeaux"
"Give Me Some Credit","team-link single-player",2,"Gxav","Gxav","/xavierconort"
"Give Me Some Credit","team-link single-player",3,"occupy","occupy","/users/2687/jmalicki"
"Event Recommendation Engine Challenge","team-link single-player",1,"jsf","jsf","/joseffeigl"
"Event Recommendation Engine Challenge","team-link team-player",2,"n_m & IM","Naokazu Mizuta","/naokazumizuta"
"Event Recommendation Engine Challenge","team-link team-player",2,"n_m & IM","Ildefons Magrans","/ildefons"
"Event Recommendation Engine Challenge","team-link single-player",3,"r0u1i","r0u1i","/users/30481/r0u1i"
"What Do You Know?","team-link single-player",1,"Steffen Rendle","Steffen Rendle","/users/25112/steffen-rendle"
"What Do You Know?","team-link single-player",2,"Alexander D\'yakonov","Alexander D\'yakonov","/dyakonov"
"What Do You Know?","team-link single-player",3,"ekla","ekla","/users/25508/pankaj-mishra"
"Photo Quality Prediction","team-link single-player",1,"B Yang","B Yang","/byang1"
"Photo Quality Prediction","team-link single-player",2,"PlanetThanet","PlanetThanet","/users/7052/jason-tigg"
"Photo Quality Prediction","team-link single-player",3,"D\'yakonov Alexander (MSU, Moscow, Russia)","D\'yakonov Alexander (MSU, Moscow, Russia)","/dyakonov"
"Predict Grant Applications","team-link single-player",1,"Jeremy Howard","Jeremy Howard","/users/3256/jeremy-howard"
"Predict Grant Applications","team-link single-player",2,"student1","student1","/quansun"
"Predict Grant Applications","team-link single-player",3,"piaomiao","piaomiao","/users/2498/yuanchen-he"
"Tradeshift Text Classification","team-link team-player",1,"carl and snow","rcarson","/jiweiliu"
"Tradeshift Text Classification","team-link team-player",1,"carl and snow","Xueer Chen","/xueerchen"
"Tradeshift Text Classification","team-link team-player",2,"Les Trois Mousquetaires","Romain Ayres","/romainayres"
"Tradeshift Text Classification","team-link team-player",2,"Les Trois Mousquetaires","Matt Sco","/mattsco"
"Tradeshift Text Classification","team-link team-player",2,"Les Trois Mousquetaires","Bibi Mining","/ericbiernat"
"Tradeshift Text Classification","team-link single-player",3,"beluga","beluga","/gaborfodor"
"See Click Predict Fix","team-link single-player",1,"J.A. Guerrero","J.A. Guerrero","/blindape"
"See Click Predict Fix","team-link team-player",2,"Bryan Gregory & Miroslaw Horbal","Bryan Gregory","/bryangregory"
"See Click Predict Fix","team-link team-player",2,"Bryan Gregory & Miroslaw Horbal","Miroslaw Horbal","/miroslaw"
"See Click Predict Fix","team-link single-player",3,"James Petterson","James Petterson","/jpetterson"
"CONNECTOMICS","team-link team-player",1,"AAAGV","Aaron","/users/165937/aaron"
"CONNECTOMICS","team-link team-player",1,"AAAGV","Antonio Sutera","/asutera"
"CONNECTOMICS","team-link team-player",1,"AAAGV","Arnaud Joly","/arjoly"
"CONNECTOMICS","team-link team-player",1,"AAAGV","Gilles Louppe","/glouppe"
"CONNECTOMICS","team-link team-player",1,"AAAGV","Vincent François","/vincfl"
"CONNECTOMICS","team-link single-player",2,"Matthias Ossadnik","Matthias Ossadnik","/mossadnik"
"CONNECTOMICS","team-link single-player",3,"Ildefons Magrans","Ildefons Magrans","/ildefons"
"Traveling Santa Problem","team-link team-player",1,"Farmers peeing further","Vlado Boza","/usamec"
"Traveling Santa Problem","team-link team-player",1,"Farmers peeing further","Farmár","/users/75989/farm-r"
"Traveling Santa Problem","team-link single-player",2,"wleite","wleite","/users/76482/wleite"
"Traveling Santa Problem","team-link single-player",3,"Rudolph","Rudolph","/users/76294/mathieu-bouchard"
"Mapping Dark Matter","team-link team-player",1,"DeepZot","danielm","/users/11851/danielm"
"Mapping Dark Matter","team-link team-player",1,"DeepZot","davidk","/users/14548/davidk"
"Mapping Dark Matter","team-link single-player",2,"Zooma","Zooma","/ccccat"
"Mapping Dark Matter","team-link team-player",3,"Ali & Eu Jin","Ali Hassaïne","/ahassaine"
"Mapping Dark Matter","team-link team-player",3,"Ali & Eu Jin","Eu Jin Lok","/ejlok1"
"Influencers in Social Networks","team-link single-player",1,"deadgeek","deadgeek","/grizzli3k"
"Influencers in Social Networks","team-link single-player",2,"MLRush","MLRush","/users/78090/mlrush"
"Influencers in Social Networks","team-link single-player",3,"Gábor S","Gábor S","/users/16398/g-bor-s"
"KDD Cup 2014 - Predicting Excitement at DonorsChoose.org","team-link team-player",1,"\'STRAYA","Yoon","/users/84255/yoon"
"KDD Cup 2014 - Predicting Excitement at DonorsChoose.org","team-link team-player",1,"\'STRAYA","Peng","/pengliu84"
"KDD Cup 2014 - Predicting Excitement at DonorsChoose.org","team-link team-player",2,"DataRobot","Xavier Conort","/xavierconort"
"KDD Cup 2014 - Predicting Excitement at DonorsChoose.org","team-link team-player",2,"DataRobot","Leustagos","/leustagos"
"KDD Cup 2014 - Predicting Excitement at DonorsChoose.org","team-link team-player",2,"DataRobot","Jeremy Achin","/users/9441/jeremy-achin"
"KDD Cup 2014 - Predicting Excitement at DonorsChoose.org","team-link single-player",3,"ChaoticExperiments (KIRAN R)","ChaoticExperiments (KIRAN R)","/users/23831/black-magic"
"MLSP 2013 Bird Classification Challenge","team-link single-player",1,"beluga","beluga","/gaborfodor"
"MLSP 2013 Bird Classification Challenge","team-link team-player",2,"Herbal Candy","W","/users/103375/w"
"MLSP 2013 Bird Classification Challenge","team-link team-player",2,"Herbal Candy","thomeou","/users/111932/thomeou"
"MLSP 2013 Bird Classification Challenge","team-link single-player",3,"Anil Thomas","Anil Thomas","/anlthms"
"ICDAR2013 - Gender Prediction from Handwriting","team-link single-player",1,"Anil Thomas","Anil Thomas","/anlthms"
"ICDAR2013 - Gender Prediction from Handwriting","team-link single-player",2,"Elliot Dawson","Elliot Dawson","/elliotdawson"
"ICDAR2013 - Gender Prediction from Handwriting","team-link single-player",3,"Alexander Larko","Alexander Larko","/alexxanderlarko"
"ICDAR2013 - Handwriting Stroke Recovery from Offline Data","team-link single-player",1,"NovemberKilo","NovemberKilo","/nagarjunakumar"
"ICDAR2013 - Handwriting Stroke Recovery from Offline Data","team-link single-player",2,"Matt Sco","Matt Sco","/mattsco"
"ICDAR2013 - Handwriting Stroke Recovery from Offline Data","team-link team-player",3,"SophomoreOlinHackers","Alec Radford","/users/85999/alec-radford"
"ICDAR2013 - Handwriting Stroke Recovery from Offline Data","team-link team-player",3,"SophomoreOlinHackers","SlaterVictoroff","/users/86420/slatervictoroff"
"See Click Predict Fix - Hackathon","team-link single-player",1,"James Petterson","James Petterson","/jpetterson"
"See Click Predict Fix - Hackathon","team-link team-player",2,"_","Shashi Godbole","/srgodbole"
"See Click Predict Fix - Hackathon","team-link team-player",2,"_","Rohan Rao","/rohanrao"
"See Click Predict Fix - Hackathon","team-link team-player",2,"_","Gauss","/madhavkumar2005"
"See Click Predict Fix - Hackathon","team-link single-player",3,"BreakfastPirate","BreakfastPirate","/users/9766/breakfastpirate"
"AMS 2013-2014 Solar Energy Prediction Contest","team-link team-player",1,"Leustagos & Titericz","Leustagos","/leustagos"
"AMS 2013-2014 Solar Energy Prediction Contest","team-link team-player",1,"Leustagos & Titericz","Gilberto Titericz Junior","/titericz"
"AMS 2013-2014 Solar Energy Prediction Contest","team-link single-player",2,"Odeillo","Odeillo","/toulouse"
"AMS 2013-2014 Solar Energy Prediction Contest","team-link single-player",3,"Owen","Owen","/owenzhang1"
"The Random Number Grand Challenge","team-link single-player",1,"ahaldenby","ahaldenby","/adrianhaldenby"
"The Random Number Grand Challenge","team-link single-player",2,"FXtest","FXtest","/vadims"
"The Random Number Grand Challenge","team-link single-player",3,"Maxwell\'s demon","Maxwell\'s demon","/sigint"
"Data Mining Hackathon on BIG DATA (7GB) Best Buy mobile web site","team-link single-player",1,"LR","LR","/users/41275/guocong-song"
"Data Mining Hackathon on BIG DATA (7GB) Best Buy mobile web site","team-link team-player",2,"RapStar","Kingsfield","/users/33714/kingsfield"
"Data Mining Hackathon on BIG DATA (7GB) Best Buy mobile web site","team-link team-player",2,"RapStar","Dragon","/users/55647/dragon"
"Data Mining Hackathon on BIG DATA (7GB) Best Buy mobile web site","team-link single-player",3,"phoneix","phoneix","/users/33580/phoneix"
"Psychopathy Prediction Based on Twitter Usage","team-link single-player",1,"y_tag","y_tag","/users/33499/y-tag"
"Psychopathy Prediction Based on Twitter Usage","team-link single-player",2,"Bruce Cragin","Bruce Cragin","/bcragin"
"Psychopathy Prediction Based on Twitter Usage","team-link team-player",3,"Indy Actuaries","Neil Schneider","/users/7657/neil-schneider"
"Psychopathy Prediction Based on Twitter Usage","team-link team-player",3,"Indy Actuaries","Shea Parkes","/users/10694/shea-parkes"
"ICDAR 2011 - Arabic Writer Identification","team-link team-player",1,"UCL","Andrew Newell","/users/6669/andrew-newell"
"ICDAR 2011 - Arabic Writer Identification","team-link team-player",1,"UCL","Lewis Griffin","/users/1356/lewis-griffin"
"ICDAR 2011 - Arabic Writer Identification","team-link single-player",2,"Lichen Liang","Lichen Liang","/users/1534/llc"
"ICDAR 2011 - Arabic Writer Identification","team-link single-player",3,"Wride","Wride","/users/4340/lvdm"
"ICFHR 2012 - Arabic Writer Identification","team-link single-player",1,"Wayne Zhang","Wayne Zhang","/waynezhang"
"ICFHR 2012 - Arabic Writer Identification","team-link team-player",2,"Newell & Griffin","Andrew Newell","/users/6669/andrew-newell"
"ICFHR 2012 - Arabic Writer Identification","team-link team-player",2,"Newell & Griffin","Lewis Griffin","/users/1356/lewis-griffin"
"ICFHR 2012 - Arabic Writer Identification","team-link single-player",3,"YT","YT","/users/4667/yanir-seroussi"
"BCI Challenge @ NER 2015","team-link team-player",1,"the overfitting avengers","Alexandre Barachant","/alexandrebarachant"
"BCI Challenge @ NER 2015","team-link team-player",1,"the overfitting avengers","Cédric Gouy-Pailler","/cedricgp"
"BCI Challenge @ NER 2015","team-link team-player",1,"the overfitting avengers","blaine","/rafalcycon"
"BCI Challenge @ NER 2015","team-link single-player",2,"Devin","Devin","/devinanzelmo"
"BCI Challenge @ NER 2015","team-link team-player",3,"H2O.ai","mlandry","/mlandry"
"BCI Challenge @ NER 2015","team-link team-player",3,"H2O.ai","David Galvin","/users/292252/david-galvin"
"BCI Challenge @ NER 2015","team-link team-player",3,"H2O.ai","RobC","/robbiec"
"Stay Alert! The Ford Challenge","team-link single-player",1,"inference","inference","/users/5484/inference"
"Stay Alert! The Ford Challenge","team-link single-player",2,"Mick Wagner","Mick Wagner","/users/5903/mick-wagner"
"Stay Alert! The Ford Challenge","team-link single-player",3,"Dekosuke","Dekosuke","/users/5549/junpei-komiyama"
"IJCNN Social Network Challenge ","team-link team-player",1,"IND CCA","Elaine Shi","/users/4983/elaine-shi"
"IJCNN Social Network Challenge ","team-link team-player",1,"IND CCA","Ben","/users/4881/ben"
"IJCNN Social Network Challenge ","team-link team-player",1,"IND CCA","Arvind Narayanan","/users/5340/arvind-narayanan"
"IJCNN Social Network Challenge ","team-link team-player",2,"wcuk","William Cukierski","/wcukierski"
"IJCNN Social Network Challenge ","team-link team-player",2,"wcuk","Ben Hamner","/benhamner"
"IJCNN Social Network Challenge ","team-link team-player",2,"wcuk","B Yang","/byang1"
"IJCNN Social Network Challenge ","team-link single-player",3,"vsh","vsh","/users/5048/vivek-sharma"
"Greek Media Monitoring Multilabel Classification (WISE 2014)","team-link single-player",1,"Alexander D\'yakonov (MSU, Moscow, Russia)","Alexander D\'yakonov (MSU, Moscow, Russia)","/dyakonov"
"Greek Media Monitoring Multilabel Classification (WISE 2014)","team-link team-player",2,"anttip","anttip","/anttip"
"Greek Media Monitoring Multilabel Classification (WISE 2014)","team-link team-player",2,"anttip","jread","/users/181606/jread"
"Greek Media Monitoring Multilabel Classification (WISE 2014)","team-link team-player",3,"honzas (Univ. of West Bohemia, Pilsen, Czechia)","honzas","/honzas"
"Greek Media Monitoring Multilabel Classification (WISE 2014)","team-link team-player",3,"honzas (Univ. of West Bohemia, Pilsen, Czechia)","Jan Vanek","/users/90795/jan-vanek"
"Chess ratings - Elo versus the Rest of the World","team-link single-player",1,"Outis","Outis","/users/2081/yannis-sismanis"
"Chess ratings - Elo versus the Rest of the World","team-link single-player",2,"Jeremy Howard","Jeremy Howard","/users/3256/jeremy-howard"
"Chess ratings - Elo versus the Rest of the World","team-link single-player",3,"pug","pug","/users/3050/martin-reichert"
"Data Mining Hackathon on (20 mb) Best Buy mobile web site - ACM SF Bay Area Chapter","team-link single-player",1,"Green Avenger","Green Avenger","/users/8819/green-avenger"
"Data Mining Hackathon on (20 mb) Best Buy mobile web site - ACM SF Bay Area Chapter","team-link single-player",2,"vdaniloff","vdaniloff","/vdaniloff"
"Data Mining Hackathon on (20 mb) Best Buy mobile web site - ACM SF Bay Area Chapter","team-link single-player",3,"CF1","CF1","/yassertabandeh"
"Personality Prediction Based on Twitter Stream","team-link single-player",1,"WL","WL","/willieliao"
"Personality Prediction Based on Twitter Stream","team-link single-player",2,"JKARP","JKARP","/jasonkarpeles"
"Personality Prediction Based on Twitter Stream","team-link single-player",3,"joshnk","joshnk","/users/2403/joshnk"
"Tourism Forecasting Part One","team-link team-player",1,"leecbaker","Lee Baker","/users/2100/lee-baker"
"Tourism Forecasting Part One","team-link team-player",1,"leecbaker","Jeremy Howard","/users/3256/jeremy-howard"
"Tourism Forecasting Part One","team-link single-player",2,"jtrigg","jtrigg","/users/701/jason-trigg"
"Tourism Forecasting Part One","team-link single-player",3,"Jtd","Jtd","/users/2868/johanna-trujillo-diaz"
"Tourism Forecasting Part Two","team-link single-player",1,"Sali Mali","Sali Mali","/users/1335/sali-mali"
"Tourism Forecasting Part Two","team-link team-player",2,"leecbaker","Lee Baker","/users/2100/lee-baker"
"Tourism Forecasting Part Two","team-link team-player",2,"leecbaker","Jeremy Howard","/users/3256/jeremy-howard"
"Tourism Forecasting Part Two","team-link single-player",3,"stratometrics","stratometrics","/users/2561/ragauss"
"Predict HIV Progression","team-link single-player",1,"Chris_R","Chris_R","/users/1744/chris-raimondi"
"Predict HIV Progression","team-link team-player",2,"Flying Pig","Grzegorz Swirszcz","/users/1461/grzegorz-swirszcz"
"Predict HIV Progression","team-link team-player",2,"Flying Pig","Claudia Perlich","/users/1542/claudia-perlich"
"Predict HIV Progression","team-link single-player",3,"chaos","chaos","/users/745/xie-chao"
"Don\'t Overfit!","team-link single-player",1,"Jose H. Solorzano","Jose H. Solorzano","/solorzano"
"Don\'t Overfit!","team-link single-player",2,"Tim Salimans","Tim Salimans","/timsalimans"
"Don\'t Overfit!","team-link single-player",3,"Outis","Outis","/users/2081/yannis-sismanis"
"Semi-Supervised Feature Learning","team-link team-player",1,"Benjamin Hamner & William Cukierski","William Cukierski","/wcukierski"
"Semi-Supervised Feature Learning","team-link team-player",1,"Benjamin Hamner & William Cukierski","Ben Hamner","/benhamner"
"Semi-Supervised Feature Learning","team-link single-player",2,"Glenngariff","Glenngariff","/users/3059/tanguy"
"Semi-Supervised Feature Learning","team-link single-player",3,"Ekip","Ekip","/users/3336/gwezboell"
"Partly Sunny with a Chance of Hashtags","team-link single-player",1,"aseveryn","aseveryn","/users/143015/aseveryn"
"Partly Sunny with a Chance of Hashtags","team-link single-player",2,"Tim Dettmers","Tim Dettmers","/users/68749/tim-dettmers"
"Partly Sunny with a Chance of Hashtags","team-link team-player",3,"Duffman & Pascal","Pascal","/pvkooten"
"Partly Sunny with a Chance of Hashtags","team-link team-player",3,"Duffman & Pascal","Duffman","/duffman"
"Challenges in Representation Learning: Facial Expression Recognition Challenge","team-link single-player",1,"RBM","RBM","/users/2412/charlie-tang"
"Challenges in Representation Learning: Facial Expression Recognition Challenge","team-link team-player",2,"Unsupervised","Unsupervised","/users/65734/unsupervised"
"Challenges in Representation Learning: Facial Expression Recognition Challenge","team-link team-player",2,"Unsupervised","Chetan Ramaiah","/chetanra"
"Challenges in Representation Learning: Facial Expression Recognition Challenge","team-link single-player",3,"Maxim Milakov","Maxim Milakov","/milakov"
"Challenges in Representation Learning: The Black Box Learning Challenge","team-link single-player",1,"doubleshot","doubleshot","/davidthaler"
"Challenges in Representation Learning: The Black Box Learning Challenge","team-link single-player",2,"sayit","sayit","/donghyun"
"Challenges in Representation Learning: The Black Box Learning Challenge","team-link single-player",3,"leif erickson","leif erickson","/users/684/dimmu"
"RecSys2013: Yelp Business Rating Prediction","team-link team-player",1,"BrickMover","Yuyu Zhang","/users/105226/yuyu-zhang"
"RecSys2013: Yelp Business Rating Prediction","team-link team-player",1,"BrickMover","Hanxiao Sun","/users/94220/hanxiao-sun"
"RecSys2013: Yelp Business Rating Prediction","team-link team-player",1,"BrickMover","Xudong Liu","/users/33595/xudong-liu"
"RecSys2013: Yelp Business Rating Prediction","team-link team-player",1,"BrickMover","Qiang Li","/users/110280/qiang-li"
"RecSys2013: Yelp Business Rating Prediction","team-link team-player",1,"BrickMover","Lu Liu","/users/111098/lu-liu"
"RecSys2013: Yelp Business Rating Prediction","team-link team-player",1,"BrickMover","Liang Pang","/liangpang"
"RecSys2013: Yelp Business Rating Prediction","team-link team-player",1,"BrickMover","Lei Shi","/users/42426/lei-shi"
"RecSys2013: Yelp Business Rating Prediction","team-link single-player",2,"vsu","vsu","/users/1664/vsu"
"RecSys2013: Yelp Business Rating Prediction","team-link single-player",3,"Merlion","Merlion","/users/113604/rubing-duan"
"The ICML 2013 Bird Challenge","team-link team-player",1,"ATD_Madbirds","Rafael Hernández Murcia","/rafahernandez"
"The ICML 2013 Bird Challenge","team-link team-player",1,"ATD_Madbirds","Víctor Suárez Paniagua","/users/88666/v-ctor-su-rez-paniagua"
"The ICML 2013 Bird Challenge","team-link single-player",2,"AMPires","AMPires","/ampires"
"The ICML 2013 Bird Challenge","team-link single-player",3,"ikretus","ikretus","/ikretus"
"The ICML 2013 Whale Challenge - Right Whale Redux","team-link team-player",1,"SluiceBox","Nick Kridler","/users/7947/nick-kridler"
"The ICML 2013 Whale Challenge - Right Whale Redux","team-link team-player",1,"SluiceBox","Scott Dobson","/users/5978/scott-dobson"
"The ICML 2013 Whale Challenge - Right Whale Redux","team-link single-player",2,"Swedish Chef","Swedish Chef","/chefele"
"The ICML 2013 Whale Challenge - Right Whale Redux","team-link single-player",3,"Daniel Nouri","Daniel Nouri","/dnouri"
"How Much Did It Rain?","team-link single-player",1,"Devin","Devin","/devinanzelmo"
"How Much Did It Rain?","team-link team-player",2,"No rain no gain.!","Μαριος Μιχαηλιδης KazAnova","/kazanova"
"How Much Did It Rain?","team-link team-player",2,"No rain no gain.!","SRK","/sudalairajkumar"
"How Much Did It Rain?","team-link team-player",3,"here comes the rain again....","Abhishek","/abhishek"
"How Much Did It Rain?","team-link team-player",3,"here comes the rain again....","vrajs5","/chevli"
"ECML/PKDD 15: Taxi Trajectory Prediction (I)","team-link team-player",1,"🚕","AdeB","/adbrebs"
"ECML/PKDD 15: Taxi Trajectory Prediction (I)","team-link team-player",1,"🚕","ÉJLS","/esimon"
"ECML/PKDD 15: Taxi Trajectory Prediction (I)","team-link team-player",1,"🚕","katchup","/katchup"
"ECML/PKDD 15: Taxi Trajectory Prediction (I)","team-link team-player",2,"ISFA_team","CYR_ISFA","/cyrisfa"
"ECML/PKDD 15: Taxi Trajectory Prediction (I)","team-link team-player",2,"ISFA_team","Jojo Boulix","/jojoboulix"
"ECML/PKDD 15: Taxi Trajectory Prediction (I)","team-link single-player",3,"kc","kc","/tyi2000"
"ECML/PKDD 15: Taxi Trip Time Prediction (II)","team-link single-player",1,"Fluxus","Fluxus","/hochthom"
"ECML/PKDD 15: Taxi Trip Time Prediction (II)","team-link single-player",2,"kc","kc","/tyi2000"
"ECML/PKDD 15: Taxi Trip Time Prediction (II)","team-link team-player",3,"BlueTaxi","bluebalam","/bluebalam"
"ECML/PKDD 15: Taxi Trip Time Prediction (II)","team-link team-player",3,"BlueTaxi","lamthuy","/lamthuy"
"ECML/PKDD 15: Taxi Trip Time Prediction (II)","team-link team-player",3,"BlueTaxi","Alessandra","/alessandra"
"ECML/PKDD 15: Taxi Trip Time Prediction (II)","team-link team-player",3,"BlueTaxi","yiannisg","/yiannisg"
"ECML/PKDD 15: Taxi Trip Time Prediction (II)","team-link team-player",3,"BlueTaxi","TurtleDonkey","/turtledonkey"
"R Package Recommendation Engine","team-link single-player",1,"One Old Dog","One Old Dog","/dslate"
"R Package Recommendation Engine","team-link single-player",2,"Record Me Men","Record Me Men","/users/394/m4xl1n"
"R Package Recommendation Engine","team-link single-player",3,"libGUNDAM","libGUNDAM","/users/4569/masaki"
"INFORMS Data Mining Contest 2010","team-link single-player",1,"dejavu","dejavu","/users/2591/cole-harris"
"INFORMS Data Mining Contest 2010","team-link single-player",2,"Swedish Chef","Swedish Chef","/chefele"
"INFORMS Data Mining Contest 2010","team-link single-player",3,"sali mali","sali mali","/users/1335/sali-mali" '
),stringsAsFactors=FALSE)
```

You can also embed plots, for example:

```{r,fig.height=6,fig.width=6,echo=FALSE,message=FALSE}
library(igraph)
library(plyr)

orig.par <- par()

# creates graph oriented data
createGraphData <- function (raw.team.df) {
  # function to transform raw team data into graph edges
  create_edges <- function(df) {
      # df:  data frame containing only members of one team
      
      edges <- t(combn(df$member.url[order(df$member.url)],2))
      colnames(edges) <- c("player1","player2")
      return(edges)
  }
  
  # create dataframe of edges
  edges.df <- ddply(subset(raw.team.df,team.type=="team-link team-player"),
               .(competition.name,team.place),create_edges)
  edges.df$player1 <- as.character(edges.df$player1)
  edges.df$player2 <- as.character(edges.df$player2)
  edges.df <- ddply(edges.df,.(player1,player2),summarize,team.count=length(player1))
  
  # create data frame for vertices
  vertices.df <- ddply(raw.team.df,.(member.url,member.name),summarize,
                       top.place=min(team.place),
                       top3.count=length(team.place))
  # handle situation where kaggle member changed profile name over time
  vertices.df <- ddply(vertices.df,.(member.url),summarize,
                       member.name=member.name[length(member.name)],  #take last name
                       top.place=min(top.place),
                       top3.count=sum(top3.count))
  vertices.df <- adply(vertices.df,1,mutate,
                       color=switch(top.place,"gold","darkgray","darkgoldenrod1"),
                       size=switch(min(top3.count,3),2,5,8))

  return(list(vertices=vertices.df, edges=edges.df))
}


# create a graph to perform initial data scrubbing
df <- subset(raw.team.df) #,competition.name=="Heritage Health Prize")
graph <- createGraphData(df)

g <- graph_from_data_frame(graph[["edges"]],directed=FALSE,vertices=graph[["vertices"]])
V(g)$label <- NA

set.seed(123)
lyt <- layout_nicely(g)

plot(g, 
     layout=lyt,
     main="Player Relationships on Winning Teams")
```


```{r,echo=FALSE,fig.height=6,fig.width=6}
top.players <- read.csv(textConnection('
"member.url","rank"
"/owenzhang1",1
"/titericz",2
"/kazanova",3
"/stasg7",4
"/abhishek",5
'
),stringsAsFactors=FALSE)

V(g)$shape <- "circle"
V(g)$frame.color <- "black"
for (member in top.players$member.url) {
    V(g)[member]$frame.color <- "red"
    V(g)[member]$label <- V(g)[member]$member.name
    V(g)[member]$label.font <- 2
}


plot(g,
     layout=lyt,
     main="Top 5 Players's Relationships")
```


```{r,echo=FALSE,fig.height=6,fig.width=6}

# function to focus on the neighbors of the top players
plotTopPlayerNeighbors <- function(one.row,g) {
  e1 <- incident_edges(g,V(g)[one.row$member.url])
  g.top.player.neighbors <- subgraph.edges(g,e1[[1]])
  V(g.top.player.neighbors)$label <- V(g.top.player.neighbors)$member.name
  V(g.top.player.neighbors)$size <- V(g.top.player.neighbors)$size * 4
  for(i in 1:length(E(g.top.player.neighbors))) {
      E(g.top.player.neighbors)[i]$width <- switch(min(E(g.top.player.neighbors)[i]$team.count,3),1,3,5)
  }
  plot(g.top.player.neighbors,
       main=paste0(V(g.top.player.neighbors)[one.row$member.url]$member.name,
                    "\nRank #",one.row$rank))
}

a_ply(top.players,1,plotTopPlayerNeighbors,g)

```

```{r,echo=FALSE}

# find community where Owen, Giberto and Stansilav are located
# extract out each community subgraph
cmnties <- decompose(g)

idx <- sapply(cmnties,function(c){"/owenzhang1" %in% V(c)$name})

g3 <- cmnties[idx][[1]]

idx <- is.na(V(g3)$label)

V(g3)[idx]$label <- V(g3)[idx]$member.name
V(g3)[idx]$label.cex <- 0.75
V(g3)$size <- V(g3)$size*1.5


plot(g3)

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
